project_name: driverkit
builds:
  - id: "driverkit"
    goos:
    - linux
    goarch:
    - amd64
    - arm64
    main: .
    flags:
      - -v 
      - -buildmode=pie
    ldflags: 
      - "{{.Env.LDFLAGS}}"
    binary: driverkit

release:
  github:
  prerelease: auto
