name: Master CI
on:
  push:
    branches: [master]

# Checks if any concurrent jobs is running for master CI and eventually cancel it
concurrency:
  group: ci-master
  cancel-in-progress: true  

jobs:
  build-test:
    strategy:
      matrix:
        arch: [amd64, arm64]
    uses: ./.github/workflows/reusable_build_test_driverkit.yml
    with:
      arch: ${{ matrix.arch }}

  push-images:
    strategy:
      matrix:
        arch: [amd64, arm64]
    uses: ./.github/workflows/reusable_build_push_images.yml
    needs: build-test
    with:
      arch: ${{ matrix.arch }}
    secrets: inherit

  images:
    uses: ./.github/workflows/reusable_manifest_images.yml
    needs: push-images
    secrets: inherit
      
    
